title: Li Lab @ NUS
description: Engineering Cell and Tissue for Regeneration and Rejuvenation
url: https://miu007.github.io/LiLabNUS

theme: jekyll-theme-slate

plugins:
  - jekyll-feed
  - jekyll-sitemap

exclude:
  - node_modules
  - vendor